services:
  battle-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: battle-service
    env_file:
      - path: ......env.rds
        required: false
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
