spring:
  application:
    name: battle-service

  datasource:
    url: jdbc:mysql://localhost:3307/battle?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

server:
  port: 8082

external:
  member-point:
    url: ${MEMBER_POINT_SERVICE_URL:http://localhost:8081}
  insight:
    url: ${INSIGHT_SERVICE_URL:http://localhost:8083}
  internal-auth-token: internal-secret-token

logging:
  level:
    com.todongsan: DEBUG
