networks:
  member-point-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: member-point-mysql
    ports:
      - "3307:3306"
    env_file:
      - ../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_MEMBERPOINT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - member-point-network

  member-point-service:
    build: .
    container_name: member-point-service
    ports:
      - "8080:8080"
    env_file:
      - ../.env
      - .env.local
    environment:
      DB_URL: jdbc:mysql://mysql:3306/${DB_MEMBERPOINT}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    networks:
      - member-point-network
    depends_on:
      - mysql
