services:
  member-point-service:
    build: .
    env_file:
      - ../..env
      - ......env.rds
    ports:
      - "8080:8080"
    networks:
      - todongsan-network

networks:
  todongsan-network:
    external: true
